export default {
  isDebug: true,
  useMock: true,
  baseURL: '/api',
  serverLocale: true,
  serverRoute: true,
  maxTabs: 10,
  isMenuCollapse: false,
  color: '#409eff',
  size: 'default',
  mode: 'auto',
  useDarkNav: true,
  useTabs: true,
  showCopyright: true,
  showBreadcrumb: true,
}
